
SquidConf:
  MonitoringIPRange: 127.0.0.1/32 192.170.227.128/32 128.135.158.191/32 188.185.0.0/17 131.225.240.232/32 128.142.0.0/16 188.184.128.0/17 188.185.48.0/20 188.185.128.0/17
  LimitEphemeralSize: 2048
  IPRange: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 72.36.84.0/22 72.36.88.0/27 72.36.100.0/24 72.36.101.0/24 72.36.102.0/24 72.36.96.0/24 192.170.226.0/23 192.170.231.0/26 128.135.158.0/25 192.170.236.0/24 128.135.112.64/26 128.135.165.66/32 128.135.158.128/25 129.114.17.0/24 129.114.18.0/24 129.114.19.0/24 129.114.104.0/24 149.165.224.0/24 149.165.225.0/24 149.165.233.0/24 149.165.234.0/24 140.247.0.0/16 149.165.156.0/24 149.165.157.0/24 149.165.158.0/24 149.165.159.0/24 149.165.160.0/24 149.165.161.0/24 149.165.162.0/24 149.165.163.0/24 149.165.164.0/24 149.165.165.0/24 149.165.166.0/24 149.165.167.0/24 149.165.168.0/24 149.165.169.0/24 149.165.170.0/24 149.165.171.0/24 149.165.172.0/24 149.165.173.0/24 149.165.174.0/24 149.165.175.0/24 128.174.118.0/24 192.17.18.32/28 129.114.58.0/24 129.114.62.161/32 129.114.59.160/27 129.114.63.32/27 206.76.192.0/19 129.8.242.0/24 192.41.230.0/23 192.41.236.0/23 141.142.0.0/16 127.0.0.1 192.41.230.0/23 192.41.236.0/23 129.79.157.0/24 2001:48A8:68F7:0001::/64 2001:48A8:68F7:8001::/64
  RequestEphemeralSize: 1024
  MaxAccessLog: !<!> 1000M
  UseHostpathLogDir: True
  CacheDirOnHost: !<!> /slate-cache/squid-cache
  Logfile_Rotate: !<!> 5
  CacheSize: !<!> 100000
  CacheMem: !<!> 16384
  DisableDiskCache: False
  CPU: 4
  LogToStdout: False
  CleanLog: False
Instance: !<!> ""
NodeSelection:
  OpenDefaultMonPort: True
  Hostname: iut2-slate.mwt2.org
Service:
  NodePort: 32200
  ExternalVisibility: NodePort
  MonitoringPort: 3401
  Port: 3128
ImageTag: testing
